const TIMEZONE_COUNTRIES: Record<string, string> = {
	"Europe/Amsterdam": "NL",
	"Europe/Brussels": "BE",
	"Europe/Berlin": "DE",
	"Europe/Paris": "FR",
	"Europe/London": "GB",
	"Europe/Dublin": "IE",
	"Europe/Madrid": "ES",
	"Europe/Lisbon": "PT",
	"Europe/Rome": "IT",
	"Europe/Vienna": "AT",
	"Europe/Zurich": "CH",
	"Europe/Copenhagen": "DK",
	"Europe/Stockholm": "SE",
	"Europe/Oslo": "NO",
	"Europe/Helsinki": "FI",
	"Europe/Warsaw": "PL",
	"Europe/Prague": "CZ",
	"Europe/Budapest": "HU",
	"Europe/Bucharest": "RO",
	"Europe/Sofia": "BG",
	"Europe/Athens": "GR",
	"Europe/Istanbul": "TR",
	"Europe/Kyiv": "UA",
	"Europe/Moscow": "RU",
	"Europe/Luxembourg": "LU",
	"America/New_York": "US",
	"America/Chicago": "US",
	"America/Denver": "US",
	"America/Phoenix": "US",
	"America/Los_Angeles": "US",
	"America/Anchorage": "US",
	"Pacific/Honolulu": "US",
	"America/Toronto": "CA",
	"America/Vancouver": "CA",
	"America/Edmonton": "CA",
	"America/Winnipeg": "CA",
	"America/Halifax": "CA",
	"America/Mexico_City": "MX",
	"America/Sao_Paulo": "BR",
	"America/Argentina/Buenos_Aires": "AR",
	"America/Santiago": "CL",
	"America/Bogota": "CO",
	"America/Lima": "PE",
	"Asia/Tokyo": "JP",
	"Asia/Seoul": "KR",
	"Asia/Shanghai": "CN",
	"Asia/Hong_Kong": "HK",
	"Asia/Taipei": "TW",
	"Asia/Singapore": "SG",
	"Asia/Bangkok": "TH",
	"Asia/Jakarta": "ID",
	"Asia/Manila": "PH",
	"Asia/Kuala_Lumpur": "MY",
	"Asia/Kolkata": "IN",
	"Asia/Karachi": "PK",
	"Asia/Dhaka": "BD",
	"Asia/Dubai": "AE",
	"Asia/Riyadh": "SA",
	"Asia/Jerusalem": "IL",
	"Africa/Cairo": "EG",
	"Africa/Lagos": "NG",
	"Africa/Nairobi": "KE",
	"Africa/Johannesburg": "ZA",
	"Africa/Casablanca": "MA",
	"Australia/Sydney": "AU",
	"Australia/Melbourne": "AU",
	"Australia/Brisbane": "AU",
	"Australia/Perth": "AU",
	"Australia/Adelaide": "AU",
	"Pacific/Auckland": "NZ",
};

/**
 * Maps common IANA timezones to ISO country codes as a last-resort geo
 * signal from the client's browser. Only covers unambiguous major zones;
 * returns null for anything unknown rather than guessing.
 */
export function countryFromTimezone(timezone: string | null | undefined): string | null {
	if (!timezone) return null;
	return TIMEZONE_COUNTRIES[timezone] ?? null;
}
