export { createAnalytics } from "./core/create-analytics";
export { remco, posthog, vercel, logger } from "./adapters";
export type {
	RemcoBuilder,
	RemcoClient,
	PosthogBuilder,
	PosthogClient,
	PosthogProvider,
	VercelBuilder,
	VercelClient,
	LoggerBuilder,
	LoggerSink,
} from "./adapters";
export { enrich, redact, filter, transform } from "./middleware";
export type {
	Adapter,
	AdapterBuilder,
	AdapterFailure,
	AdapterSource,
	Analytics,
	AnalyticsEvent,
	Builder,
	Context,
	ContextInput,
	ErrorHandler,
	EventDraft,
	EventHandler,
	EventKind,
	EventMap,
	HandlerOutcome,
	Middleware,
	Primitive,
	Properties,
	RuntimeConfig,
	ScopedEvents,
	SendResult,
	Stage,
	Targets,
	Traits,
	Value,
} from "./types";
