export type ViewColumn = { name: string; type: string; description: string };

export type QueryView = { name: string; description: string; columns: ViewColumn[] };

type Row = [name: string, type: string, description: string];

function columns(rows: Row[]): ViewColumn[] {
  return rows.map(([name, type, description]) => ({ name, type, description }));
}

const eventColumns: Row[] = [
  ["event_id", "text", "The SDK's UUIDv7 id"],
  ["project_id", "text", "Project slug"],
  ["name", "text", "pageview, click, signup, ..."],
  ["ts", "timestamptz", "When it happened, clock-corrected"],
  ["received_at", "timestamptz", "When the API received it"],
  ["visitor_id", "text", "Links to visitors"],
  ["session_id", "text", "Links to sessions"],
  ["host", "text", "The site's host"],
  ["path", "text", "The page path"],
  ["route", "text", "The route template, such as /blog/[slug]"],
  ["referrer", "text", "The full referrer"],
  ["referrer_domain", "text", "The referrer's domain"],
  ["channel", "text", "direct, search, social, ..."],
  ["utm_source", "text", "Campaign source"],
  ["utm_medium", "text", "Campaign medium"],
  ["utm_campaign", "text", "Campaign name"],
  ["utm_term", "text", "Campaign term"],
  ["utm_content", "text", "Campaign content"],
  ["country", "text", "From the IP address"],
  ["region", "text", "From the IP address"],
  ["city", "text", "From the IP address"],
  ["continent", "text", "From the IP address"],
  ["timezone", "text", "From the IP address"],
  ["latitude", "double precision", "City centre"],
  ["longitude", "double precision", "City centre"],
  ["device", "text", "desktop, mobile, tablet, bot or unknown"],
  ["browser", "text", "From the user agent"],
  ["browser_version", "text", "From the user agent"],
  ["os", "text", "From the user agent"],
  ["os_version", "text", "From the user agent"],
  ["screen", "text", "Screen size from the browser"],
  ["viewport", "text", "Viewport size from the browser"],
  ["language", "text", "Browser language"],
  ["connection", "text", "Connection type from the browser"],
  ["asn", "integer", "Network number"],
  ["as_org", "text", "Network owner"],
  ["props", "jsonb", "The event's own fields, such as props->>'plan'"],
  ["release", "text", "App version sent by the SDK"],
  ["bot_score", "smallint", "0 to 100; 50 and up is a bot"],
  ["bot_reasons", "text[]", "Why it was scored as a bot"],
  ["is_human", "boolean", "Not a bot, not internal, not localhost, not a preview"],
  ["is_internal", "boolean", "Your own traffic"],
  ["is_localhost", "boolean", "Sent from localhost"],
  ["is_preview", "boolean", "Sent from a preview deployment"],
  ["issue_id", "bigint", "For errors, the issue it was grouped into"],
];

/**
 * @name queryViews
 * @description The views the SQL console can read, in the `query` schema, with their columns,
 * types and a one-line description each. `/v2/query/schema` serves this list, and a test checks
 * it against the migrated views so the two cannot drift apart.
 *
 * @example
 * queryViews.map((view) => view.name);
 */
export const queryViews: QueryView[] = [
  {
    name: "events",
    description: "One row per event: pageviews, custom events, clicks, errors.",
    columns: columns(eventColumns),
  },
  {
    name: "pageviews",
    description: "Pageviews with the per-page facts of the visit joined in.",
    columns: columns([
      ...eventColumns,
      ["time_on_page_ms", "bigint", "Time until the next page, null on the last page"],
      ["scroll_depth", "real", "Deepest scroll on this page in the visit, 0 to 1"],
      ["is_entry", "boolean", "First page of the visit"],
      ["is_exit", "boolean", "Last page of the visit"],
      ["previous_path", "text", "The page before, null on the entry page"],
      ["next_path", "text", "The page after, null on the exit page"],
      ["page_number", "integer", "Position in the visit, 1 for the entry page"],
    ]),
  },
  {
    name: "sessions",
    description: "One row per visit.",
    columns: columns([
      ["session_id", "text", "The visit's id"],
      ["project_id", "text", "Project slug"],
      ["visitor_id", "text", "Links to visitors"],
      ["visit_number", "integer", "1 for the visitor's first visit, 2 for the second, ..."],
      ["since_previous_visit_ms", "bigint", "Gap since the previous visit, null on the first"],
      ["started_at", "timestamptz", "First event"],
      ["ended_at", "timestamptz", "Last event"],
      ["duration_ms", "bigint", "Time on the site"],
      ["pageviews", "integer", "Pageviews in this visit"],
      ["events", "integer", "Events in this visit"],
      ["is_bounce", "boolean", "One pageview and no interaction"],
      ["entry_path", "text", "First page"],
      ["entry_route", "text", "First page's route template"],
      ["exit_path", "text", "Last page"],
      ["exit_route", "text", "Last page's route template"],
      ["referrer_domain", "text", "How this visit started"],
      ["channel", "text", "How this visit started"],
      ["utm_source", "text", "Campaign source"],
      ["utm_campaign", "text", "Campaign name"],
      ["country", "text", "From the IP address"],
      ["city", "text", "The visitor's latest known city"],
      ["device", "text", "desktop, mobile, tablet, bot or unknown"],
      ["browser", "text", "The visitor's latest known browser"],
      ["os", "text", "The visitor's latest known operating system"],
      ["bot_score", "smallint", "0 to 100; 50 and up is a bot"],
      ["is_human", "boolean", "Not a bot and not internal"],
      ["is_internal", "boolean", "Your own traffic"],
    ]),
  },
  {
    name: "visitors",
    description: "One row per visitor per project.",
    columns: columns([
      ["visitor_id", "text", "The visitor's id"],
      ["project_id", "text", "Project slug"],
      ["first_seen", "timestamptz", "First event"],
      ["last_seen", "timestamptz", "Latest event"],
      ["visits", "integer", "Lifetime visits"],
      ["pageviews", "integer", "Lifetime pageviews"],
      ["events", "integer", "Lifetime events"],
      ["total_duration_ms", "bigint", "Lifetime time on the site"],
      ["is_returning", "boolean", "More than one visit"],
      ["user_id", "text", "Set after identify"],
      ["traits", "jsonb", "From identify, such as traits->>'plan'"],
      ["experiments", "jsonb", "Experiment variants seen"],
      ["first_referrer_domain", "text", "How they first arrived"],
      ["first_channel", "text", "How they first arrived"],
      ["first_utm_campaign", "text", "How they first arrived"],
      ["country", "text", "Latest known"],
      ["city", "text", "Latest known"],
      ["device", "text", "Latest known"],
      ["browser", "text", "Latest known"],
      ["os", "text", "Latest known"],
      ["is_internal", "boolean", "Marked as your own"],
    ]),
  },
  {
    name: "people",
    description: "Identified users across projects.",
    columns: columns([
      ["user_id", "text", "The id sent to identify"],
      ["first_seen", "timestamptz", "First event in any project"],
      ["last_seen", "timestamptz", "Latest event in any project"],
      ["first_project", "text", "Where they first came in"],
      ["projects", "text[]", "Every project they used"],
      ["visits", "integer", "Across projects"],
      ["traits", "jsonb", "Latest traits"],
    ]),
  },
  {
    name: "web_vitals",
    description: "One row per measured web vital.",
    columns: columns([
      ["vital_id", "text", "The measurement's id"],
      ["project_id", "text", "Project slug"],
      ["session_id", "text", "Links to sessions"],
      ["ts", "timestamptz", "When it was measured"],
      ["metric", "text", "lcp, inp, cls, fcp or ttfb"],
      ["value", "double precision", "Milliseconds, or a score for cls"],
      ["rating", "text", "good, needs-improvement or poor"],
      ["route", "text", "Route template"],
      ["path", "text", "Page path"],
      ["device", "text", "desktop, mobile or tablet"],
      ["country", "text", "From the IP address"],
      ["connection", "text", "Connection type"],
      ["selector", "text", "The element behind the measurement"],
      ["sample_rate", "real", "Share of page loads measured"],
      ["navigation_type", "text", "navigate, reload, back-forward, ..."],
      ["bot_score", "smallint", "0 to 100; 50 and up is a bot"],
      ["is_human", "boolean", "Not a bot and not internal"],
      ["is_internal", "boolean", "Your own traffic"],
      ["is_preview", "boolean", "From a preview deployment"],
    ]),
  },
  {
    name: "issues",
    description: "One row per grouped error.",
    columns: columns([
      ["issue_id", "bigint", "The issue's id"],
      ["project_id", "text", "Project slug"],
      ["fingerprint", "text", "What groups errors into this issue"],
      ["title", "text", "Error type and message"],
      ["culprit", "text", "Where it was thrown"],
      ["level", "text", "error or warning"],
      ["status", "text", "open, resolved or ignored"],
      ["count", "integer", "Occurrences"],
      ["visitors", "integer", "Visitors affected"],
      ["first_seen", "timestamptz", "First occurrence"],
      ["last_seen", "timestamptz", "Latest occurrence"],
      ["first_release", "text", "Release it first appeared in"],
      ["last_release", "text", "Release it last appeared in"],
      ["resolved_at", "timestamptz", "When it was resolved"],
    ]),
  },
  {
    name: "daily",
    description: "Pre-aggregated daily counts per dimension value, fast for long ranges.",
    columns: columns([
      ["project_id", "text", "Project slug"],
      ["day", "date", "UTC day"],
      ["dimension", "text", "Which dimension value counts"],
      ["value", "text", "The dimension value"],
      ["visitors", "integer", "Visitors that day"],
      ["sessions", "integer", "Sessions that day"],
      ["pageviews", "integer", "Pageviews that day"],
      ["events", "integer", "Events that day"],
    ]),
  },
  {
    name: "daily_vitals",
    description: "Pre-aggregated web vital percentiles per day, route, device and metric.",
    columns: columns([
      ["project_id", "text", "Project slug"],
      ["day", "date", "UTC day"],
      ["route", "text", "Route template"],
      ["device", "text", "desktop, mobile or tablet"],
      ["metric", "text", "lcp, inp, cls, fcp or ttfb"],
      ["samples", "integer", "Measurements that day"],
      ["p50", "double precision", "Median"],
      ["p75", "double precision", "75th percentile"],
      ["p90", "double precision", "90th percentile"],
      ["p95", "double precision", "95th percentile"],
      ["p99", "double precision", "99th percentile"],
      ["good", "integer", "Measurements rated good"],
      ["needs_improvement", "integer", "Measurements rated needs-improvement"],
      ["poor", "integer", "Measurements rated poor"],
    ]),
  },
];
